
GmshElementType = [0] * 20;

GmshElementType[1 ]="2-node line"
GmshElementType[2 ]="3-node triangle"
GmshElementType[3 ]="4-node quadrangle"
GmshElementType[4 ]="4-node tetrahedron"
GmshElementType[5 ]="8-node hexahedron"
GmshElementType[6 ]="6-node prism"
GmshElementType[7 ]="5-node pyramid"
GmshElementType[8 ]="3-node second order line (2 nodes associated with the vertices and 1 with the edge)"
GmshElementType[9 ]="6-node second order triangle (3 nodes associated with the vertices and 3 with the edges)"
GmshElementType[10]="9-node second order quadrangle (4 nodes associated with the vertices, 4 with the edges and 1 with the face)"
GmshElementType[11]="10-node second order tetrahedron (4 nodes associated with the vertices and 6 with the edges)"
GmshElementType[12]="27-node second order hexahedron (8 nodes associated with the vertices, 12 with the edges, 6 with the faces and 1 with the volume)"
GmshElementType[13]="18-node second order prism (6 nodes associated with the vertices, 9 with the edges and 3 with the quadrangular faces)"
GmshElementType[14]="14-node second order pyramid (5 nodes associated with the vertices, 8 with the edges and 1 with the quadrangular face)"
GmshElementType[15]="1-node point"
GmshElementType[16]="8-node second order quadrangle (4 nodes associated with the vertices and 4 with the edges)"
GmshElementType[17]="20-node second order hexahedron (8 nodes associated with the vertices and 12 with the edges)"
GmshElementType[18]="15-node second order prism (6 nodes associated with the vertices and 9 with the edges)"
GmshElementType[19]="13-node second order pyramid (5 nodes associated with the vertices and 8 with the edges)"
